---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: deepl
  namespace: {{ include "common.names.namespace" $ }}
spec:
  endpoints:
    - fqdn:
        hostname: deepl.{{ include "common.names.namespace" $ }}.svc.cluster.local
        port: 8080
