apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: lightbridge-main-db
  namespace: converse
spec:
  configuration:
    destinationPath: s3://ai-ops-backups/lightbridge-cnpg-backups/
    endpointURL: https://s3.ssegning.me
    s3Credentials:
      accessKeyId:
        name: lightbridge-cnpg-s3
        key: s3_access_key_id
      secretAccessKey:
        name: lightbridge-cnpg-s3
        key: s3_secret_access_key
    wal:
      compression: gzip