apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: lightbridge-main-db
  namespace: converse
spec:
  configuration:
    destinationPath: s3://ai-ops-backups/lightbridge-cnpg-backups/
    endpointURL: https://s3.ssegning.me
    s3Credentials:
      accessKeyId:
        name: lightbridge-cnpg-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: lightbridge-cnpg-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip