apiVersion: v2
name: models
description: AI model backends and routing configuration chart - deploys Backend, AIServiceBackend, AIGatewayRoute, and security policies
type: application
version: 1.1.0
appVersion: "1.0.0"


dependencies:
  - name: common
    version: '*'
    repository: "file://../common"
    tags:
      - common
      - bitnami-common