{{- if .Values.authConfigs }}
{{- range $name, $config := .Values.authConfigs }}
---
apiVersion: authorino.kuadrant.io/v1beta3
kind: AuthConfig
metadata:
  name: {{ include "common.names.name" $ }}-{{ $name }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  {{ with $config.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{ end }}

  {{ with $config.authentication }}
  authentication:
    {{- toYaml . | nindent 4 }}
  {{ end }}

  {{ with $config.metadata }}
  metadata:
    {{- toYaml . | nindent 4 }}
  {{ end }}

  {{ with $config.authorization }}
  authorization:
    {{- toYaml . | nindent 4 }}
  {{ end }}

  {{ with $config.response }}
  response:
    {{- toYaml . | nindent 4 }}
  {{ end }}

{{- end }}
{{- end }}
