{{ with .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.global.configmap.name }}
  namespace: {{ include "common.names.namespace" $ }}
data:
  "config.yaml": |
    {{- $json := . | toYaml -}}
    {{- $value := include "common.tplvalues.render" ( dict "value" $json "context" $ ) -}}
    {{ $value | nindent 4 }}
{{ end }}
