{{- with .Values.config }}
{{- $geminiPatchEnabled := false -}}
{{- $root := $ -}}
{{- $persistence := index $root.Values "proxy" "persistence" -}}
{{- if and $persistence (hasKey $persistence "gemini-patch") -}}
{{-   $geminiPatchEnabled = index (index $persistence "gemini-patch") "enabled" -}}
{{- end -}}
{{- $settings := omit .litellm_settings "callbacks" }}
{{- if $geminiPatchEnabled }}
{{- $settings = merge $settings (dict "callbacks" (list "litellm_gemini_patch.proxy_handler_instance")) }}
{{- end }}
{{- $combined := dict "litellm_settings" $settings "model_list" .model_list -}}
{{- $value := include "common.tplvalues.render" ( dict "value" ($combined | toYaml) "context" $root ) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.global.configmap.name }}
  namespace: {{ include "common.names.namespace" $ }}
data:
  "config.yaml": |
    {{ $value | nindent 4 }}
{{- end }}
