apiVersion: v2
name: core-gateway
description: Core Envoy Gateway configuration
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: '*'
    repository: "file://../common"
