{{- if .Values.upstream }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "z-image-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "z-image-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
{{- end }}
