apiVersion: v2
name: pgdump-backup
description: Automated PostgreSQL backup and restore solution for CloudNativePG clusters
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: bjw-template
    version: 4.6.2
    repository: file://../bjw-template
