apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "model-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
  annotations:
    serving.kserve.io/deploymentMode: {{ .Values.inferenceService.deploymentMode | quote }}
    serving.kserve.io/enable-prometheus-scraping: "true"
    {{- if eq .Values.inferenceService.deploymentMode "Serverless" }}
    autoscaling.knative.dev/maxScale: {{ .Values.inferenceService.maxReplicas | quote }}
    {{- if .Values.inferenceService.scaleDownDelay }}
    autoscaling.knative.dev/scale-down-delay: {{ .Values.inferenceService.scaleDownDelay | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.inferenceService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  predictor:
    maxReplicas: {{ .Values.inferenceService.maxReplicas }}

    {{- if .Values.inferenceService.timeout }}
    timeout: {{ .Values.inferenceService.timeout }}
    {{- end }}

    {{- if eq .Values.inferenceService.deploymentMode "Serverless" }}
    scaleMetric: {{ .Values.inferenceService.scaleMetric | default "concurrency" }}
    scaleTarget: {{ .Values.inferenceService.scaleTarget | default 10 }}
    {{- end }}

    {{- with .Values.inferenceService.runtimeClassName }}
    runtimeClassName: {{ . }}
    {{- end }}

    model:
      modelFormat:
        {{- toYaml .Values.model.format | nindent 8 }}

      runtime: {{ include "model-serving.inferenceRuntimeRef" . }}

      storageUri: {{ include "model-serving.resolvedStorageUri" . | trim | quote }}

      {{- with .Values.model.args }}
      args:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.model.volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    {{- with .Values.inferenceService.volumes }}
    volumes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
