global:
  litellm:
    version: "v1.82.3-stable"
  configmap:
    name: "litellm-config"

proxy:
  service:
    litellm:
      enabled: true
      annotations: { }
      type: ClusterIP
      controller: litellm
      ports:
        http:
          enabled: true
          port: 4000
          targetPort: 4000

  controllers:
    litellm:
      type: deployment
      strategy: RollingUpdate
      replicas: 1
      pod:
        labels:
          app: proxy-app
      containers:
        litellm:
          image:
            repository: docker.litellm.ai/berriai/litellm
            tag: "{{ .Values.global.litellm.version }}"
          args:
            - --config
            - /app/config.yaml
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: "Europe/Berlin"

            LITELLM_MODE: "production"

            REDIS_URL: "redis://redis-master.redis-system.svc.cluster.local:6379"

            GEMINI_API_KEY:
              secretKeyRef:
                name: gemini-api-key
                key: apiKey

            #LITELLM_MASTER_KEY:
            #  secretKeyRef:
            #    name: proxy-api-key
            #    key: apiKey

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 200Mi
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false

  persistence:
    config:
      enabled: true
      type: configMap
      name: '{{ .Values.global.configmap.name }}'
      advancedMounts:
        litellm:
          litellm:
            - path: /app/config.yaml
              subPath: config.yaml
              readOnly: true

config:
  litellm_settings:
    cache: True
    cache_params: # set cache params for redis
      type: redis
      namespace: "litellm.caching.caching"
  model_list:
    - model_name: "*"
      litellm_params:
        model: "*"