cluster:
  name: coder-cnpg
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: coder
      owner: coder

objectStore:
  name: coder-barman-store
  destinationPath: s3://ai-ops-backups/coder-cnpg-backups/
  endpointURL: https://s3.ssegning.me
  secretName: coder-cnpg-s3
