apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: context7
  namespace: {{ include "common.names.namespace" $ }}
spec:
  parentRefs:
    - name: {{ include "common.tplvalues.render" ( dict "value" .Values.gatewayRef.name "context" $ ) }}
      namespace: {{ include "common.tplvalues.render" ( dict "value" .Values.gatewayRef.namespace "context" $ ) }}
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/context7"

  backendRefs:
    - name: context7
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: context7-token
