{{- range $routeName, $routeConfig := .Values.models }}
{{- if (default true $routeConfig.enabled) }}
{{/* Filter and Validate Backends */}}
{{- $activeBackends := dict -}}
{{- range $bKey, $bVal := $routeConfig.backends }}
  {{- if (default true $bVal.enabled) }}
    {{- $_ := set $activeBackends $bKey $bVal -}}
  {{- end }}
{{- end }}

{{- if lt (len $activeBackends) 2 }}
  {{- fail (printf "Route '%s' must have at least 2 enabled backends. Found: %d" $routeName (len $activeBackends)) }}
{{- end }}

---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: {{ $routeName }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.gatewayRef.name }}
      namespace: {{ $.Values.gatewayRef.namespace }}
  llmRequestCosts:
    - metadataKey: llm_input_token
      type: InputToken
    - metadataKey: llm_cached_input_token
      type: CachedInputToken
    - metadataKey: llm_output_token
      type: OutputToken
    - metadataKey: llm_total_token
      type: TotalToken
    {{ if eq $routeConfig.kind "text" }}
    - metadataKey: llm_custom_total_cost
      type: CEL
      cel: "((input_tokens - cached_input_tokens) * {{ $routeConfig.inputPer1M }}) + (cached_input_tokens * {{ $routeConfig.cachedInputPer1M }}) + (output_tokens * {{ $routeConfig.outputPer1M }})"
    {{ end }}
    {{ if eq $routeConfig.kind "image" }}
    - metadataKey: llm_custom_total_cost
      type: CEL
      cel: "total_tokens * {{ $routeConfig.effectivePer1M }}"
    {{ end }}
    {{ if eq $routeConfig.kind "embedding" }}
    - metadataKey: llm_custom_total_cost
      type: CEL
      cel: "total_tokens * {{ $routeConfig.effectivePer1M }}"
    {{ end }}
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: {{ default $routeName }}
      modelsOwnedBy: GIS AI Models
      backendRefs:
        {{- range $bKey, $bVal := $activeBackends }}
        {{- $backendBase := index $.Values.backends $bVal.ref }}
        - name: {{ $backendBase.resourceName }}
          {{- if $bVal.modelNameOverride }}
          modelNameOverride: {{ $bVal.modelNameOverride }}
          {{- end }}
          weight: {{ $bVal.weight | default 1 }}
          priority: {{ $bVal.priority | default 0 }}
        {{- end }}
{{- end }}
{{- end }}
