apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  config.yaml: |
    litellm_settings:
      drop_params: true
    model_list:
      - model_name: kimi-k2-instruct-0905
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/kimi-k2-instruct-0905
      - model_name: kimi-k2-thinking
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/kimi-k2-thinking
      - model_name: deepseek-v3p2
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/deepseek-v3p2
      - model_name: glm-5
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/glm-5
      - model_name: kimi-k2.5
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/kimi-k2p5
      - model_name: cogito-671b-v2-p1
        litellm_params:
          model: fireworks_ai/accounts/cogito/models/cogito-671b-v2-p1
      - model_name: qwen3-reranker-8b
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-reranker-8b
      - model_name: qwen3-embedding-8b
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-embedding-8b
      - model_name: qwen3-8b
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-8b
      - model_name: minimax-m2p5
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/minimax-m2p5
      - model_name: qwen3-vl-30b-a3b-instruct
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-vl-30b-a3b-instruct
      - model_name: qwen3-vl-30b-a3b-thinking
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-vl-30b-a3b-thinking
