{{- include "bjw-s.common.loader.init" . }}

{{- define "keycloak-baseline.hardcodedValues" -}}
{{- if not .Values.global.nameOverride }}
global:
  nameOverride: "keycloak-baseline"
{{- end }}
{{- if not .Values.keycloak.url }}
keycloak:
  url: "http://keycloak.keycloak.svc.cluster.local:8080"
{{- end }}
{{- end -}}

{{- $_ := mergeOverwrite .Values (include "keycloak-baseline.hardcodedValues" . | fromYaml) -}}

{{- include "bjw-s.common.loader.generate" . -}}