{{- if .Values.realm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-baseline.realm.configMapName" . }}
  namespace: {{ .Values.global.keycloak.namespace | default "keycloak" }}
  labels:
    {{- include "keycloak-baseline.labels" . | nindent 4 }}
    app.kubernetes.io/component: realm-config
data:
  {{ .Values.realm.name }}-realm.json: |
    {{- include "keycloak-baseline.realm.json" . | nindent 4 }}
{{- end -}}