apiVersion: v2
name: kuadrant-policies
description: Kuadrant Auth and RateLimit policies
type: application
version: 1.2.1
appVersion: "1.0.0"

dependencies:
  - name: common
    version: '*'
    repository: "file://../common"
    tags:
      - common
      - bitnami-common
