apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: librechat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
      - name: librechat
        image: ghcr.io/danny-avila/librechat:v0.8.3-rc1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3080
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Berlin"
        - name: ALLOW_EMAIL_LOGIN
          value: "false"
        - name: ALLOW_REGISTRATION
          value: "false"
        - name: ALLOW_SOCIAL_LOGIN
          value: "true"
        - name: ALLOW_SOCIAL_REGISTRATION
          value: "true"
        - name: REFRESH_TOKEN_EXPIRY
          value: "5184000000"
        - name: OPENID_ISSUER
          value: "https://accounts.camer.digital/realms/camer-digital"
        - name: OPENID_CALLBACK_URL
          value: "/oauth/openid/callback"
        - name: OPENID_SCOPE
          value: "openid profile email librechat"
        - name: OPENID_REQUIRED_ROLE
          value: "user"
        - name: OPENID_REQUIRED_ROLE_TOKEN_KIND
          value: "access"
        - name: OPENID_REQUIRED_ROLE_PARAMETER_PATH
          value: "librechat_roles"
        - name: OPENID_AUTO_REDIRECT
          value: "true"
        - name: ANTHROPIC_API_KEY
          value: "user_provided"
        - name: OPENAI_API_KEY
          value: "user_provided"
        - name: GOOGLE_KEY
          value: "user_provided"
        - name: DOMAIN_CLIENT
          value: "https://ai.camer.digital"
        - name: DOMAIN_SERVER
          value: "https://ai.camer.digital"
        - name: NO_INDEX
          value: "true"
        - name: USE_REDIS
          value: "true"
        - name: REDIS_KEY_PREFIX
          value: "librechat-prod-v2"
        - name: REDIS_URI
          value: "redis://redis-master.redis-system.svc.cluster.local:6379"
        - name: FORCED_IN_MEMORY_CACHE_NAMESPACES
          value: "APP_CONFIG,CONFIG_STORE"
        - name: SEARCH
          value: "true"
        - name: MEILI_HOST
          value: "http://librechat-search:7700"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-meili-config
              key: MEILI_MASTER_KEY
        - name: MONGO_URI
          value: "mongodb://converse-db-0.converse-db-headless:27017"
        - name: CREDS_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-config
              key: creds_key
        - name: CREDS_IV
          valueFrom:
            secretKeyRef:
              name: librechat-config
              key: creds_iv
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: librechat-config
              key: jwt_secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: librechat-config
              key: jwt_refresh_secret
        - name: CONVERSE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-main-config
              key: converse_openai_api_key
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-websearch-config
              key: serper_api_key
        - name: FIRECRAWL_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-websearch-config
              key: firecrawl_api_key
        - name: JINA_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-websearch-config
              key: jina_api_key
        - name: IMAGE_GEN_OAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-main-config
              key: converse_openai_api_key
        - name: IMAGE_GEN_OAI_BASEURL
          value: "http://ai-gateway-internal/v1"
        - name: OPENID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: librechat-openid-config
              key: client_id
        - name: OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: librechat-openid-config
              key: client_secret
        - name: OPENID_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: librechat-openid-config
              key: session_secret
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: librechat-s3-config
              key: s3_region_name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: librechat-s3-config
              key: s3_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: librechat-s3-config
              key: s3_secret_access_key
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: librechat-s3-config
              key: s3_bucket_name
        volumeMounts:
        - name: config
          mountPath: /app/librechat.yaml
          subPath: librechat.yaml
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: librechat-config
