{{- if .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
type: Opaque
{{- else if .Values.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat-admin-panel.fullname" . }}-secret
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
type: Opaque
data:
  session_secret: {{ .Values.sessionSecret | b64enc | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat-admin-panel.fullname" . }}-secret
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
type: Opaque
data:
  session_secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
