{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat-admin-panel.fullname" . }}-secret
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
type: Opaque
data:
  session_secret: {{ default (randAlphaNum 32) .Values.sessionSecret | b64enc | quote }}
{{- end }}
