apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-internal
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  selector:
    gateway.envoyproxy.io/gateway-name: {{ .Values.gateway.name }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
