apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuerName }}
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  listeners:
  - name: api-https
    hostname: {{ .Values.gateway.listeners.api.hostname }}
    port: {{ .Values.gateway.listeners.api.port }}
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.tls.secretName }}
    allowedRoutes:
      namespaces:
        from: All
  - name: web-https
    hostname: "*.ai.camer.digital"
    port: {{ .Values.gateway.listeners.web.port }}
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.tls.secretName }}
    allowedRoutes:
      namespaces:
        from: All
