apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "core-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ include "core-gateway.fullname" . }}
  connection:
    bufferLimit: 100Mi
  retry:
    numRetries: 5
    perRetry:
      backOff:
        baseInterval: 100ms
        maxInterval: 10s
      timeout: 30s
    retryOn:
      httpStatusCodes:
        - 500
        - 502
        - 503
        - 504
        - 404
      triggers:
        - connect-failure
        - retriable-status-codes