apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ include "core-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ include "core-gateway.fullname" . }}
  connection:
    bufferLimit: 100Mi
  headers:
    enableEnvoyHeaders: true