apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "core-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.issuer | default "self-signed-ca" }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "eg" }}
  listeners:
    - name: api-https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.apiHostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "core-gateway.fullname" . }}-api-tls
            kind: Secret
    - name: web-https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.webHostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "core-gateway.fullname" . }}-web-tls
            kind: Secret
