---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "core-gateway.fullname" . }}-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    goal: redirector
spec:
  parentRefs:
    - name: {{ include "core-gateway.fullname" . }}
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
