apiVersion: v2
name: librechat-admin-panel
description: A Helm chart for LibreChat Admin Panel - standalone management interface

type: application

version: 0.1.0

appVersion: "latest"

icon: https://raw.githubusercontent.com/ClickHouse/librechat-admin-panel/main/public/favicon.png

keywords:
  - librechat
  - admin
  - clickhouse
  - management

dependencies:
  - name: app-template
    version: '4.6.2'
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: admin-panel

  - name: common
    version: '*'
    repository: "file://../common"
    tags:
      - common
      - bitnami-common
