{{ with .Values.gateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-helper
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  ports:
    - name: https-{{ .port }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .port }}
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "common.names.fullname" $ }}-helper
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
      - port: {{ .port }}
{{ end }}
