apiVersion: v1
kind: ConfigMap
metadata:
  name: lightbridge-config-template
  namespace: {{ .Release.Namespace | default .Values.namespace }}
data:
  config.yaml: |
    server:
      rest:
        address: "0.0.0.0"
        port: 3000
      grpc:
        address: "0.0.0.0"
        port: 3001
    logging:
      level: "info"
    database:
      url: "{{`{{DATABASE_URL}}`}}"
      pool_size: 10
    oauth2:
      jwks_url: "{{`{{JWKS_URL}}`}}"
