apiVersion: v1
kind: Service
metadata:
  name: lightbridge
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  selector:
    app: lightbridge
  ports:
    - name: http
      port: {{ .Values.lightbridge.service.port }}
      targetPort: rest
    - name: grpc
      port: {{ .Values.lightbridge.service.grpcPort }}
      targetPort: grpc
