apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.gateway.name }}-authorino
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      sectionNames:
        - api-https
  extAuth:
    grpc:
      backendRefs:
        - group: ''
          name: {{ .Values.authorino.serviceName }}
          namespace: {{ .Values.authorino.namespace }}
          port: {{ .Values.authorino.port }}
          kind: Service
