{{- if and .Values.tls.enabled .Values.tls.redirectToHttps }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: {{ .Release.Name }}-redirect-308
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: "{{ .Values.namespace | default .Release.Namespace }}/{{ .Values.gateway.name }}/http"
      operation:
        # Patching indices 1 and 2 which correspond to our actual domains
        # Index 0 is a wildcard host that doesn't have a redirect
        op: add
        path: /virtual_hosts/1/routes/0/redirect/response_code
        value: "PERMANENT_REDIRECT"
    - type: "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
      name: "{{ .Values.namespace | default .Release.Namespace }}/{{ .Values.gateway.name }}/http"
      operation:
        op: add
        path: /virtual_hosts/2/routes/0/redirect/response_code
        value: "PERMANENT_REDIRECT"
{{- end }}
