{{- if .Values.cluster -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name | default "postgres-cluster" }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.cluster.instances | default 1 }}
  storage:
    size: {{ .Values.cluster.storage.size | default "10Gi" }}
  {{- with .Values.cluster.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if .Values.cluster.bootstrap }}
  bootstrap:
    {{- toYaml .Values.cluster.bootstrap | nindent 4 }}
  {{- end }}
{{- end }}
