{{- if .Values.objectStore -}}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Values.objectStore.name | default "coder-barman-store" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
    destinationPath: {{ .Values.objectStore.destinationPath | default "s3://ai-ops-backups/coder-cnpg-backups/" }}
    endpointURL: {{ .Values.objectStore.endpointURL | default "https://s3.ssegning.me" }}
    s3Credentials:
      accessKeyId:
        name: {{ .Values.objectStore.secretName | default "coder-cnpg-s3" }}
        key: s3_access_key_id
      secretAccessKey:
        name: {{ .Values.objectStore.secretName | default "coder-cnpg-s3" }}
        key: s3_secret_access_key
      region:
        name: {{ .Values.objectStore.secretName | default "coder-cnpg-s3" }}
        key: s3_region_name
{{- end }}
