{{- define "coder-db.s3.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: coder-s3-config
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  s3_access_key_id: {{ .Values.s3.accessKeyId }}
  s3_secret_access_key: {{ .Values.s3.secretAccessKey }}
  s3_region_name: {{ .Values.s3.region | default "us-east-1" }}
{{- end }}

{{- define "coder-db.objectstore" -}}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: coder-barman-store
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
    destinationPath: s3://ai-ops-backups/coder-cnpg-backups/
    endpointURL: https://s3.ssegning.me
    s3Credentials:
      accessKeyId:
        name: coder-s3-config
        key: s3_access_key_id
      secretAccessKey:
        name: coder-s3-config
        key: s3_secret_access_key
      region:
        name: coder-s3-config
        key: s3_region_name
{{- end }}

{{- define "coder-db.cluster" -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-cnpg
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 2
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: coder-barman-store
        serverName: coder-cnpg
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: coder
      owner: coder
{{- end }}

{{- define "coder-db.scheduled-backup" -}}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: coder-cnpg-daily
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  immediate: true
  schedule: "0 0 2 * * *"
  cluster:
    name: coder-cnpg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}

---
{{ include "coder-db.s3.secret" . }}
---
{{ include "coder-db.objectstore" . }}
---
{{ include "coder-db.cluster" . }}
---
{{ include "coder-db.scheduled-backup" . }}
